services:
  - type: web
    name: larkbot-production
    env: node
    # Set root directory to the larkbot subdirectory in the repo
    rootDir: Development/larkbot
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    
    envVars:
      - key: NODE_ENV
        value: production
      # PORT is automatically set by Render, don't override it
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_WEBHOOKS
        value: "true"
      - key: ENABLE_CHATBOT
        value: "true"
      - key: ENABLE_MONITORING
        value: "true"
      - key: ENABLE_RATE_LIMITING
        value: "true"
      - key: DEBUG_MODE
        value: "false"
        
    # These should be set as secret environment variables in Render dashboard
    # - INTERCOM_TOKEN
    # - INTERCOM_APP_ID  
    # - INTERCOM_WEBHOOK_SECRET
    # - LARK_APP_ID
    # - LARK_APP_SECRET
    # - LARK_WEBHOOK_SECRET
    # - LARK_CHAT_GROUP_ID
    # - WEBHOOK_SECRET
    
    healthCheckPath: /health
    
    # Domains and networking
    domains:
      - larkbot-production.onrender.com
      
    # Auto-deploy settings
    autoDeploy: true
    branch: main
    
    # Runtime settings - use Node.js version from package.json
    # runtime: nodejs18
    
    # Scaling settings
    numInstances: 1
        
    # Pre-deploy commands
    # preDeployCommand: |
    #   npm ci --only=production
      
    # Post-deploy commands are optional
    # postDeployCommand: |
    #   echo "Larkbot deployment completed successfully"